
SEL = 0;

MENU_SETTINGS = [];

enum SETTINGS_ARR {
	STRING,
	SCALE,
	VAL,
	MIN,
	MAX
}

MENU_SETTINGS[0, SETTINGS_ARR.STRING] = "Score to Win"
MENU_SETTINGS[0, SETTINGS_ARR.SCALE] = 1
MENU_SETTINGS[0, SETTINGS_ARR.VAL] = global.scoreToWin;
MENU_SETTINGS[0, SETTINGS_ARR.MIN] = 1;
MENU_SETTINGS[0, SETTINGS_ARR.MAX] = 10;

MENU_SETTINGS[1, SETTINGS_ARR.STRING] = "Fixed Camera"
MENU_SETTINGS[1, SETTINGS_ARR.SCALE] = 1
MENU_SETTINGS[1, SETTINGS_ARR.VAL] = bool(false);
MENU_SETTINGS[1, SETTINGS_ARR.MIN] = false;
MENU_SETTINGS[1, SETTINGS_ARR.MAX] = true;
